#!/usr/bin/env python
import os
import remote
import sys

MY_DIR = os.path.dirname( __file__ )
PUPPET_DIR = os.path.join( MY_DIR, "puppet")

s = remote.VMSSH()

# Copy/untar data to /srv


# Copy/untar secrets to /srv


# Install the puppet config
print "Transferring new puppet config...",
sys.stdout.flush()
s.push_dir( "./puppet", PUPPET_DIR, remove_remote = True )
print "done."

# Apply the puppet config

