#!/usr/bin/env python
import os
import remote
import sys

MY_DIR = os.path.dirname( __file__ )
PUPPET_DIR = os.path.join( MY_DIR, "puppet")

s = remote.VMSSH()

# Copy/untar data to /srv
print "Transferring secrets...",
sys.stdout.flush()
s.push_dir( os.path.join( MY_DIR, "secrets" ),
            "/srv/secrets",
            remove_remote = True,
            mode = "0700" )
print "done."

# Copy/untar secrets to /srv


# Install the puppet config
print "Transferring new puppet config...",
sys.stdout.flush()
s.push_dir( PUPPET_DIR, "/etc/puppet", remove_remote = True )
print "done."

# Apply the puppet config
r = s.exec_command( "puppet apply /etc/puppet/manifests/sr-dev.pp" )

while True:
    c = 0

    for f in r[1:]:
        l = f.readline()
        if l == "":
            c += 1
        else:
            print l.strip()

    if c == 2:
        break

r[0].channel.recv_exit_status()

