#!/usr/bin/env python
import sys
import vm

if len(sys.argv) not in (2,3):
    print >>sys.stderr, "Usage: new-disk-set NAME [BASENAME]"
    exit(1)

NAME = sys.argv[1]

BASENAME = "base"
if len(sys.argv) >= 3:
    BASENAME = sys.argv[2]

v = vm.VM()
v.create_set( NAME, BASENAME )
