#!/usr/bin/env python
import argparse
import sys
import vm

parser = argparse.ArgumentParser( "Run the VM" )

parser.add_argument( "--save-changes",
                     dest="save_changes", default=False,
                     action = "store_true",
                     help="Save changes made to the guest's disks" )

parser.add_argument( "--disk-set", type=str,
                     dest="disk_set", default="base",
                     help="Name of the disk set to use" )

args = parser.parse_args()

snapshot = not args.save_changes

v = vm.VM( snapshot = snapshot )

v.set_disk_set( args.disk_set )

v.run()

v.p.wait()
